# permissions for end users to edit podpresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podpreset-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - podpresets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - podpresets/status
  verbs:
  - get
