kubectl apply -f crds/redhatcop_v1alpha1_podpreset_crd.yaml
kubectl apply -f  service_account.yaml
kubectl apply -f clusterrole.yaml
kubectl apply -f cluster_role_binding.yaml
kubectl apply -f role
kubectl apply -f role.yaml
kubectl apply -f role_binding.yaml
kubectl apply -f secret.yaml
kubectl apply -f webhook.yaml
