apiVersion: apps/v1
kind: Deployment
metadata:
  name: podpreset-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      name: podpreset-webhook
  template:
    metadata:
      labels:
        name: podpreset-webhook
    spec:
      serviceAccountName: podpreset-webhook
      containers:
        - name: podpreset-webhook
          image: gcr.io/vb-datatransformation/podpreset-webhook:latest
          command:
            - podpreset-webhook
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "podpreset-webhook"
          ports:
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /tmp/cert
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: podpreset-webhook-cert
